#!/bin/bash
VERSION=25.7f
set -euo pipefail
FAKETIME_PATH=`which tbl2asn | sed 's=bin/tbl2asn=lib/faketime/libfaketime.so.1='`

LD_PRELOAD=${FAKETIME_PATH} \
  FAKETIME="2019-01-01 00:00:01" \
  real-tbl2asn "${@:1}"
